name: 'gdelt'
version: '1.0.0'
config-version: 2

profile: 'gdelt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  gdelt:
    staging:
      +materialized: view
      +database: GDELT_SILVER_DEV
      +schema: STAGING
    marts:
      +materialized: table
      +database: GDELT_GOLD_DEV
      +schema: MARTS