name: 'gdelt'
version: '1.0.0'
config-version: 2

profile: 'gdelt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  gdelt:
    staging:
      +materialized: view
      +database: "{{ env_var('DBT_SILVER_DB', 'GDELT_SILVER_DEV') }}"
      +schema: STAGING
      intermediate:
        +materialized: table
        +database: "{{ env_var('DBT_SILVER_DB', 'GDELT_SILVER_DEV') }}"
        +schema: INTERMEDIATE
    marts:
      +materialized: table
      +database: "{{ env_var('DBT_GOLD_DB', 'GDELT_GOLD_DEV') }}"
      +schema: MARTS
      principal:
        +materialized: table
        +database: "{{ env_var('DBT_GOLD_DB', 'GDELT_GOLD_DEV') }}"
        +schema: PRINCIPAL

seeds:
  gdelt:
    +database: "{{ env_var('DBT_BRONZE_DB', 'GDELT_BRONZE_DEV') }}"
    +schema: SEEDS